### PR TITLE
MM 14040 : update marked for parentheses in link url

### LINKED ISSUE #10407: Inline link with nested parentheses does not work
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14040)

Original report: https://forum.mattermost.org/t/inline-link-with-nested-parentheses-does-not-work/6651

*Summary*
Not a regression.
Posting an inline link with nested parentheses in the URL does not work.

*Steps to reproduce*
1. Post this message: " how about: [hmm](https://somewhere?param=(currentUser()))? "

*Expected behavior*
Expect inline link with title hmm and URL https://somewhere?param=(currentUser())

*Observed behavior*
No inline link. The original markdown syntax appears directly. However, part of the URL (https://somewhere?param=) is then detected as an auto link and becomes clickable.

### PR DESCRIPTION
**Pull request by scottleedavis**
#### Summary

Modifies the href regex pattern search to include embedded parentheses
e.g. `[hmmm](https://somewhere/?param=(currentUser()))`

#### Jira
Fixes https://github.com/mattermost/mattermost-server/issues/10407

#### other repositories

Supporting https://github.com/mattermost/mattermost-webapp/pull/2814

### CODE REVIEW

**Comment by scottleedavis** [comment]
I am experiencing one error in `npm run test` for mattermost-webapp with this change.

```
    Expected value to be equal to:
      "<p>test.:test</p>"
    Received:
      "<p><a class=\"theme markdown__link\" href=\"test.:test\" rel=\"noreferrer\" target=\"_blank\">test.:test</a></p>"
```

I will look into this more.

**Comment by scottleedavis** [comment]
The above error occurs on master and is not related to the change in this PR

**Comment by scottleedavis** [comment]
Please let me know if I could make this fix as well in this PR so as to be able to pull it into webapp.  :)

**Comment by hanzei** [comment]
@hmhealey Can you help with this?

**Comment by hmhealey** [comment]
@scottleedavis If you update your webapp branch off the latest master, mattermost/mattermost-webapp#2842 was just merged which modifies that test to support some recent changes made to our marked fork

File: lib/marked.js [hunk 1]
```diff
@@ -505,7 +505,7 @@ inline._punctuation = '!"#$%&\'()*+,\\-./:;<=>?@\\[^_{|}~';
 inline.em = edit(inline.em).replace(/punctuation/g, inline._punctuation).getRegex();
 
 inline._inside = /(?:\[[^\]]*\]|[^\[\]]|\](?=[^\[]*\]))*/;
-inline._href = /(?:[^()]|\([^()]*\))*/;
+inline._href = /(?:[^()]*|\([^()]*\)*)*/;
```
Comment (hmhealey) [inline lib/marked.js]: The asterisk in the first part of this doesn't do anything since it basically turns that part of the regex into `(?:[^()]*)*` which causes a lot of problems in a regex.

You can simplify the `[^()]` pattern to just `a` to see the problem better. If you do that here, you end up with the pattern `(?:a*)*`. The problem with that pattern as well as the original is that it can cause some performance issues because it can group the letters in a string in many different ways when searching for a match. For example, if you have a string like `aaaa` and you try to find a match for either of those patterns, they will both check for matches by grouping the letters like `(aaaa)`, `(aaa)(a)`, `(aa)(aa)`, `(aa)(a)(a)`, and so on which causes the code to check an exponentially increasing number of different cases. Without the extra asterisk, those patterns would look like `(?:[^()])*` and `(?:a)*`, and they only groups the letters one way: `(a)(a)(a)(a)`.

The second part of this also has the same issue because you've made the final bracket optional, so you also end up with basically `(?:\(a*)*` which exhibits the same issue as long as there's an opening bracket somewhere in the string.

It's actually impossible to use regular expressions to parse arbitrarily nested brackets, so I don't have any particularly good advice for solving this for any number of nested brackets outside of just implementing proper URL parsing. If you want to add support for brackets nested two deep (like `(())` as in the ticket), you could look at the `gfm.url` regex below since that should support that. It is a lot more complex as you can see though.

**Review by hmhealey — CHANGES_REQUESTED** [review]
This isn't going to work because regular expressions cannot parse arbitrarily nested brackets. Also, this particular expression has some cases where catastrophic backtracking (one of my favourite programming words) happens. If you run `npm test` in this repo, you'll see where this gets stuck on one of the tests because that's happening.

File: lib/marked.js (hunk 1 above)
Comment (scottleedavis) [reply lib/marked.js]: Thanks @hmhealey.  Regex's have not been my strong suite, but very open to improving upon that.  I just tried using the gfm.url regex though had some test failures.  I will look more into this.

I also tried some of the regex's from the main marked repo, though they didn't pass tests either.  The latest 6.2 release does parse the double () correctly, so I am hopeful a solution can be found for the ticket.

Comment (hmhealey) [reply lib/marked.js]: Yeah, I saw theirs. I'm surprised it's more complicated than ours, but that's probably to support things like nested brackets.

Also, yeah, regexes are hard. I've mostly learned about them the hard way by breaking Mattermost by adding things just like that. 😛

**Comment by scottleedavis** [comment]
@hmhealey I've updated the regex in a way I am not sure is idiomatic, however all the tests pass and the original issue url of `https://somewhere/?param=(currentUser())` parses correctly, as well in the webapp markdown example.

**Comment by hmhealey** [comment]
Unfortunately, this still has issues with certain bad URLs. This pattern has issues because the `[^*]` in `\([^*]*\)` can match opening and closing brackets which leads to bad behaviour with a string like `[link]((((((((((((((((((((((((((((((((((((((((((((((((((((()`.

Without ditching regexes entirely, I think our only option would be to support brackets nested one level deep so `?params=(currentUser())` would work, but `?params=(currentUser(id()))` would not. It's impossible to create a regex that supports arbitrarily nested brackets, so that's the best we can do without creating more and more complex regexes

**Comment by scottleedavis** [comment]
Ok updated with my best effort to only do one level deep as requested `/(?:[^()]|\([^()]*\)|\S*\(?\([^()]*\)\))*/`.  Happy to improve upon it or try something else.  Tested that your second example `?params=(currentUser(id()))` does not match.

**Comment by hanzei** [comment]
@hmhealey Would you please review again?

File: lib/marked.js [hunk 2]
```diff
@@ -505,7 +505,7 @@ inline._punctuation = '!"#$%&\'()*+,\\-./:;<=>?@\\[^_{|}~';
 inline.em = edit(inline.em).replace(/punctuation/g, inline._punctuation).getRegex();
 
 inline._inside = /(?:\[[^\]]*\]|[^\[\]]|\](?=[^\[]*\]))*/;
-inline._href = /(?:[^()]|\([^()]*\))*/;
+inline._href = /(?:[^()]|\([^()]*\)|\S*\(?\([^()]*\)\))*/;
```
Comment (hmhealey) [inline lib/marked.js]: A few things about this regex:
1. Why have the `\S*` in the third part of the regex? I don't think we should need whitespace before nested brackets.
2. Why make the first opening bracket optional with `\(?`? It should probably just be `\(` since this otherwise allows for mismatched brackets
3. The third part of the regex doesn't allow for things like `(abc(123))` or `((abc)123(xyz))` where there are multiple sets of nested brackets.

I think this might work
```suggestion
inline._href = /(?:[^()]|\([^()]*\)|\((?:[^()]*\([^()]*\))+[^()]*\))*/;
```
I think this might work since the third group would now match
```
\(             // an outer set of brackets containing
(?:
    [^()]*     // some text
    \(         // followed by matching brackets
    [^()]*     // containing some more text
    \)
)+             // repeated any number of times
[^()]*         // and then finally followed by some more text
\)
```

**Review by hmhealey — CHANGES_REQUESTED** [review]
Can you also add some tests for this new behaviour? Since regexes are rather complex, we should make sure to cover a good number of these nested URLs

**Comment by scottleedavis** [comment]
I added 14 tests for the nested urls.  Do you recommend I change anything or make additions?

**Review by hmhealey — APPROVED** [review]

**Comment by hmhealey** [comment]
Looks good. I tried to see if there were any more cases that caused catastrophic backtracking with this, but it seems solid to me.

**Comment by hmhealey** [comment]
Now that this is merged, would you mind submitting a PR to the web app branch to update its version of the library?
